INSERT INTO PAYER2 (CODEG, ANNEE, INDICERETROCESSIONG)
VALUES (
  (SELECT CODEG FROM (
      SELECT CODEG FROM GAMME
      ORDER BY DBMS_RANDOM.VALUE
  ) WHERE ROWNUM = 1),
  (SELECT ANNEE FROM (
      SELECT ANNEE FROM CALENDRIER4
      ORDER BY DBMS_RANDOM.VALUE
  ) WHERE ROWNUM = 1),
  9000
);
