CREATE INDEX IDX_EMPLOYES_NOM_PRENOM ON EMPLOYES (NOME, PRENOME);

CREATE INDEX IDX_USINES_NOM ON USINES (NOMU);

CREATE INDEX IDX_AVOIR_TYPE_CODETU ON AVOIR_TYPE (CODETU);

CREATE INDEX IDX_TYPEU_NOM ON TYPEU (NOMTU);

CREATE INDEX IDX_PV_NOM_TYPE ON POINTS_DE_VENTE (NOMPV, TYPEPV);
