TYPEU = ["chaine assemblage", "scierie", "métallurgie", "fonderie"]

GAMMES = [
    "jardin et piscine", "mobilier intérieur", "plomberie et chauffage", "salle de bain et WC",
    "luminaire", "électricité et domotique", "quincaillerie", "cuisine",
    "peinture et droguerie", "carrelage et parquet", "matériaux de construction"
]

DEPTS = ["fabrication", "assemblage", "RH", "expédition", "logistique", "direction", "finance"]

PV_TYPES = ["GSB", "Brico-Express"]

PV_NAMES = {
    "GSB": [
        "Brico Dépôt", "Leroy Merlin", "Castorama", "Weldom", "Bricomarché",
        "Point P", "Gedimat", "BigMat", "Brico Pro", "Mr.Bricolage",
        "Bricoman", "Brico Cash", "La Plateforme du Bâtiment", "Brico Leclerc",
        "Brico Centre", "Entrepôt du Bricolage", "Brico Arche", "King Jouet Bricolage"
    ],
    "Brico-Express": [
        "Brico Express"
    ]
}

# Bases
QUALIFICATIONS_PROBABILITIES = {
    3: 0.20,  # CAP, BEP
    4: 0.30,  # Bac Pro, BP, Bac
    5: 0.20,  # BTS, DUT
    6: 0.15,  # Licence Pro, BUT, Licence
    7: 0.10,   # Master
    8: 0.05,   # Doctorat
}

QUALIFICATIONS = {
    # Niveau: [(diplome_complet, salaire_min, salaire_max, base_diplome)]
    3: [
        # Bases
        ("CAP", 11.0, 15.0),
        ("BEP", 11.5, 15.0),
        # Spécialisations
        ("CAP Électricien", 11.5, 16.0, "CAP"),
        ("BEP Chaîne Assemblage", 11.5, 15.0, "BEP"),
        ("BEP Scierie", 11.5, 15.0, "BEP"),
        ("BEP Métallurgie", 11.5, 15.0, "BEP"),
        ("BEP Fonderie", 11.5, 15.0, "BEP"),
        ("BEP Fabrication", 11.5, 15.0, "BEP"),
        ("BEP Assemblage", 11.5, 15.0, "BEP"),
        ("BEP RH", 11.5, 15.0, "BEP"),
        ("BEP Expédition", 11.5, 15.0, "BEP"),
        ("BEP Logistique", 11.5, 15.0, "BEP"),
        ("BEP Direction", 11.5, 15.0, "BEP"),
        ("BEP Finance", 11.5, 15.0, "BEP"),
        ("CAP Chaîne Assemblage", 11.0, 15.0, "CAP"),
        ("CAP Scierie", 11.0, 15.0, "CAP"),
        ("CAP Métallurgie", 11.0, 15.0, "CAP"),
        ("CAP Fonderie", 11.0, 15.0, "CAP"),
        ("CAP Fabrication", 11.0, 15.0, "CAP"),
        ("CAP Assemblage", 11.0, 15.0, "CAP"),
        ("CAP RH", 11.0, 15.0, "CAP"),
        ("CAP Expédition", 11.0, 15.0, "CAP"),
        ("CAP Logistique", 11.0, 15.0, "CAP"),
        ("CAP Direction", 11.0, 15.0, "CAP"),
        ("CAP Finance", 11.0, 15.0, "CAP"),
    ],
    4: [
        # Bases
        ("Bac Pro", 13.0, 17.0),
        ("BP", 14.0, 18.0),
        ("Bac", 13.0, 16.5),
        # Spécialisations BP
        ("BP Chaîne Assemblage", 14.0, 18.0, "BP"),
        ("BP Scierie", 14.0, 18.0, "BP"),
        ("BP Métallurgie", 14.0, 18.0, "BP"),
        ("BP Fonderie", 14.0, 18.0, "BP"),
        ("BP Fabrication", 14.0, 18.0, "BP"),
        ("BP Assemblage", 14.0, 18.0, "BP"),
        ("BP RH", 14.0, 18.0, "BP"),
        ("BP Expédition", 14.0, 18.0, "BP"),
        ("BP Logistique", 14.0, 18.0, "BP"),
        ("BP Direction", 14.0, 18.0, "BP"),
        ("BP Finance", 14.0, 18.0, "BP"),
        # Spécialisations Bac Pro
        ("Bac Pro Électrotechnique", 13.5, 18.0, "Bac Pro"),
        ("Bac Pro Chaîne Assemblage", 13.0, 17.0, "Bac Pro"),
        ("Bac Pro Scierie", 13.0, 17.0, "Bac Pro"),
        ("Bac Pro Métallurgie", 13.0, 17.0, "Bac Pro"),
        ("Bac Pro Fonderie", 13.0, 17.0, "Bac Pro"),
        ("Bac Pro Fabrication", 13.0, 17.0, "Bac Pro"),
        ("Bac Pro Assemblage", 13.0, 17.0, "Bac Pro"),
        ("Bac Pro RH", 13.0, 17.0, "Bac Pro"),
        ("Bac Pro Expédition", 13.0, 17.0, "Bac Pro"),
        ("Bac Pro Logistique", 13.0, 17.0, "Bac Pro"),
        ("Bac Pro Direction", 13.0, 17.0, "Bac Pro"),
        ("Bac Pro Finance", 13.0, 17.0, "Bac Pro"),
    ],
    5: [
        # Bases
        ("BTS", 15.0, 22.0),
        ("DUT", 15.5, 22.0),
        # Spécialisations
        ("DUT Chaîne Assemblage", 15.5, 22.0, "DUT"),
        ("DUT Scierie", 15.5, 22.0, "DUT"),
        ("DUT Métallurgie", 15.5, 22.0, "DUT"),
        ("DUT Fonderie", 15.5, 22.0, "DUT"),
        ("DUT Fabrication", 15.5, 22.0, "DUT"),
        ("DUT Assemblage", 15.5, 22.0, "DUT"),
        ("DUT RH", 15.5, 22.0, "DUT"),
        ("DUT Expédition", 15.5, 22.0, "DUT"),
        ("DUT Logistique", 15.5, 22.0, "DUT"),
        ("DUT Direction", 15.5, 22.0, "DUT"),
        ("DUT Finance", 15.5, 22.0, "DUT"),
        ("BTS Électrotechnique", 15.5, 23.0, "BTS"),
        ("BTS Chaîne Assemblage", 15.0, 22.0, "BTS"),
        ("BTS Scierie", 15.0, 22.0, "BTS"),
        ("BTS Métallurgie", 15.0, 22.0, "BTS"),
        ("BTS Fonderie", 15.0, 22.0, "BTS"),
        ("BTS Fabrication", 15.0, 22.0, "BTS"),
        ("BTS Assemblage", 15.0, 22.0, "BTS"),
        ("BTS RH", 15.0, 22.0, "BTS"),
        ("BTS Expédition", 15.0, 22.0, "BTS"),
        ("BTS Logistique", 15.0, 22.0, "BTS"),
        ("BTS Direction", 15.0, 22.0, "BTS"),
        ("BTS Finance", 15.0, 22.0, "BTS"),
    ],
    6: [
        # Bases
        ("Licence Pro", 18.0, 24.0),
        ("BUT", 18.5, 25.0),
        ("Licence", 18.0, 23.5),
        # Spécialisations Licence Pro
        ("Licence Pro Chaîne Assemblage", 18.0, 24.0, "Licence Pro"),
        ("Licence Pro Scierie", 18.0, 24.0, "Licence Pro"),
        ("Licence Pro Métallurgie", 18.0, 24.0, "Licence Pro"),
        ("Licence Pro Fonderie", 18.0, 24.0, "Licence Pro"),
        ("Licence Pro Fabrication", 18.0, 24.0, "Licence Pro"),
        ("Licence Pro Assemblage", 18.0, 24.0, "Licence Pro"),
        ("Licence Pro RH", 18.0, 24.0, "Licence Pro"),
        ("Licence Pro Expédition", 18.0, 24.0, "Licence Pro"),
        ("Licence Pro Logistique", 18.0, 24.0, "Licence Pro"),
        ("Licence Pro Direction", 18.0, 24.0, "Licence Pro"),
        ("Licence Pro Finance", 18.0, 24.0, "Licence Pro"),
        # Spécialisations BUT
        ("BUT Chaîne Assemblage", 18.5, 25.0, "BUT"),
        ("BUT Scierie", 18.5, 25.0, "BUT"),
        ("BUT Métallurgie", 18.5, 25.0, "BUT"),
        ("BUT Fonderie", 18.5, 25.0, "BUT"),
        ("BUT Fabrication", 18.5, 25.0, "BUT"),
        ("BUT Assemblage", 18.5, 25.0, "BUT"),
        ("BUT RH", 18.5, 25.0, "BUT"),
        ("BUT Expédition", 18.5, 25.0, "BUT"),
        ("BUT Logistique", 18.5, 25.0, "BUT"),
        ("BUT Direction", 18.5, 25.0, "BUT"),
        ("BUT Finance", 18.5, 25.0, "BUT"),
        # Spécialisations Licence
        ("Licence Pro Métiers de l'Électricité", 18.5, 25.0, "Licence"),
        ("Licence Chaîne Assemblage", 18.0, 23.5, "Licence"),
        ("Licence Scierie", 18.0, 23.5, "Licence"),
        ("Licence Métallurgie", 18.0, 23.5, "Licence"),
        ("Licence Fonderie", 18.0, 23.5, "Licence"),
        ("Licence Fabrication", 18.0, 23.5, "Licence"),
        ("Licence Assemblage", 18.0, 23.5, "Licence"),
        ("Licence RH", 18.0, 23.5, "Licence"),
        ("Licence Expédition", 18.0, 23.5, "Licence"),
        ("Licence Logistique", 18.0, 23.5, "Licence"),
        ("Licence Direction", 18.0, 23.5, "Licence"),
        ("Licence Finance", 18.0, 23.5, "Licence"),
    ],
    7: [
        # Bases
        ("Master", 22.0, 30.0),
        ("Ingénieur", 24.0, 35.0),
        # Spécialisations
        ("Ingénieur Chaîne Assemblage", 24.0, 35.0, "Ingénieur"),
        ("Ingénieur Scierie", 24.0, 35.0, "Ingénieur"),
        ("Ingénieur Métallurgie", 24.0, 35.0, "Ingénieur"),
        ("Ingénieur Fonderie", 24.0, 35.0, "Ingénieur"),
        ("Ingénieur Fabrication", 24.0, 35.0, "Ingénieur"),
        ("Ingénieur Assemblage", 24.0, 35.0, "Ingénieur"),
        ("Ingénieur RH", 24.0, 35.0, "Ingénieur"),
        ("Ingénieur Expédition", 24.0, 35.0, "Ingénieur"),
        ("Ingénieur Logistique", 24.0, 35.0, "Ingénieur"),
        ("Ingénieur Direction", 24.0, 35.0, "Ingénieur"),
        ("Ingénieur Finance", 24.0, 35.0, "Ingénieur"),
        ("Master Énergétique et Électrique", 23.0, 32.0, "Master"),
        ("Master Chaîne Assemblage", 22.0, 30.0, "Master"),
        ("Master Scierie", 22.0, 30.0, "Master"),
        ("Master Métallurgie", 22.0, 30.0, "Master"),
        ("Master Fonderie", 22.0, 30.0, "Master"),
        ("Master Fabrication", 22.0, 30.0, "Master"),
        ("Master Assemblage", 22.0, 30.0, "Master"),
        ("Master RH", 22.0, 30.0, "Master"),
        ("Master Expédition", 22.0, 30.0, "Master"),
        ("Master Logistique", 22.0, 30.0, "Master"),
        ("Master Direction", 22.0, 30.0, "Master"),
        ("Master Finance", 22.0, 30.0, "Master"),
    ],
    8: [
        # Bases
        ("Doctorat", 28.0, 40.0),
        # Spécialisations Doctorat
        ("Doctorat en Génie Électrique", 29.0, 42.0, "Doctorat"),
        ("Doctorat Chaîne Assemblage", 28.0, 40.0, "Doctorat"),
        ("Doctorat Scierie", 28.0, 40.0, "Doctorat"),
        ("Doctorat Métallurgie", 28.0, 40.0, "Doctorat"),
        ("Doctorat Fonderie", 28.0, 40.0, "Doctorat"),
        ("Doctorat Fabrication", 28.0, 40.0, "Doctorat"),
        ("Doctorat Assemblage", 28.0, 40.0, "Doctorat"),
        ("Doctorat RH", 28.0, 40.0, "Doctorat"),
        ("Doctorat Expédition", 28.0, 40.0, "Doctorat"),
        ("Doctorat Logistique", 28.0, 40.0, "Doctorat"),
        ("Doctorat Direction", 28.0, 40.0, "Doctorat"),
        ("Doctorat Finance", 28.0, 40.0, "Doctorat"),
    ],
}

SMICS = [
    {"date": "2024-11-01", "montant": 1801.80, "augmentation": 34.88, "pourcentage": 0.02},
    {"date": "2024-01-01", "montant": 1766.92, "augmentation": 19.72, "pourcentage": 0.0113},
    {"date": "2023-05-01", "montant": 1747.20, "augmentation": 37.92, "pourcentage": 0.0221},
    {"date": "2023-01-01", "montant": 1709.28, "augmentation": 30.67, "pourcentage": 0.0183},
    {"date": "2022-08-01", "montant": 1678.95, "augmentation": 33.37, "pourcentage": 0.0203},
    {"date": "2022-05-01", "montant": 1645.58, "augmentation": 42.46, "pourcentage": 0.0264},
    {"date": "2022-01-01", "montant": 1603.12, "augmentation": 13.65, "pourcentage": 0.0086},
    {"date": "2021-10-01", "montant": 1589.47, "augmentation": 49.05, "pourcentage": 0.0319},
    {"date": "2021-01-01", "montant": 1554.58, "augmentation": 14.16, "pourcentage": 0.0092},
    {"date": "2020-01-01", "montant": 1539.42, "augmentation": 18.20, "pourcentage": 0.012},
    {"date": "2019-01-01", "montant": 1521.22, "augmentation": 22.75, "pourcentage": 0.0152},
    {"date": "2018-01-01", "montant": 1498.47, "augmentation": 17.75, "pourcentage": 0.012},
    {"date": "2017-01-01", "montant": 1480.27, "augmentation": 13.65, "pourcentage": 0.0093},
    {"date": "2016-01-01", "montant": 1466.62, "augmentation": 8.84, "pourcentage": 0.0061},
    {"date": "2015-01-01", "montant": 1457.52, "augmentation": 12.14, "pourcentage": 0.0084},
    {"date": "2014-01-01", "montant": 1445.38, "augmentation": 7.84, "pourcentage": 0.0055},
    {"date": "2013-01-01", "montant": 1430.22, "augmentation": 27.25, "pourcentage": 0.0195},
    {"date": "2012-07-01", "montant": 1425.67, "augmentation": 27.25, "pourcentage": 0.0195},
    {"date": "2012-01-01", "montant": 1398.37, "augmentation": 4.55, "pourcentage": 0.0033},
    {"date": "2011-12-01", "montant": 1393.82, "augmentation": 28.82, "pourcentage": 0.0212},
    {"date": "2011-01-01", "montant": 1365.00, "augmentation": 21.23, "pourcentage": 0.0158},
    {"date": "2010-01-01", "montant": 1343.77, "augmentation": 26.27, "pourcentage": 0.02},
    {"date": "2009-07-01", "montant": 1337.70, "augmentation": 16.62, "pourcentage": 0.0126},
    {"date": "2008-07-01", "montant": 1321.02, "augmentation": 12.14, "pourcentage": 0.0093},
    {"date": "2008-05-01", "montant": 1308.88, "augmentation": 12.14, "pourcentage": 0.0094},
    {"date": "2007-07-01", "montant": 1280.07, "augmentation": 25.79, "pourcentage": 0.0205},
    {"date": "2006-07-01", "montant": 1254.28, "augmentation": 26.40, "pourcentage": 0.0216},
    {"date": "2005-07-01", "montant": 1217.88, "augmentation": 37.21, "pourcentage": 0.0316},
    {"date": "2004-07-01", "montant": 1286.09, "augmentation": 70.98, "pourcentage": 0.0581},
    {"date": "2003-07-01", "montant": 1215.11, "augmentation": 60.84, "pourcentage": 0.0527},
    {"date": "2002-07-01", "montant": 1154.27, "augmentation": 26.94, "pourcentage": 0.0239},
    {"date": "2001-07-01", "montant": 1127.23, "augmentation": 26.94, "pourcentage": 0.0245},
    {"date": "2000-07-01", "montant": 1094.00, "augmentation": None, "pourcentage": None},
]

# calcul the avg % augmentation over the years
SMIC_AVG = 0
count = 0
for smic in SMICS:
    if smic["pourcentage"] is not None:
        SMIC_AVG += smic["pourcentage"]
        count += 1
SMIC_AVG /= count
SMIC_AVG = round(SMIC_AVG, 4)

# marques{ gamme: [marque1, marque2, ...] }
MARQUES = {
    "jardin et piscine": [
        "Gardena", "Husqvarna", "Kärcher", "Bosch", "Makita", "Stihl", "Intex", "Bestway", "Gré", "Ubbink", "Aquazendo", "Ribiland", "Oase", "Claber", "Vilmorin"
    ],
    "mobilier intérieur": [
        "IKEA", "Conforama", "Maisons du Monde", "Habitat", "Alinéa", "Fly", "H&H", "Roche Bobois", "La Redoute", "Cuir Center", "Miliboo", "BoConcept", "Poltronesofà", "Ligne Roset", "Meubles Gautier"
    ],
    "plomberie et chauffage": [
        "Grohe", "Hansgrohe", "Jacob Delafon", "Franke", "Atlantic", "Thermor", "Saunier Duval", "Vaillant", "Ariston", "De Dietrich", "Chaffoteaux", "Fleck", "SFA", "Duravit", "Ideal Standard"
    ],
    "salle de bain et WC": [
        "Jacob Delafon", "Duravit", "Grohe", "Hansgrohe", "Ideal Standard", "Villeroy & Boch", "Allibert", "Geberit", "Porcher", "Laufen", "Roca", "SFA", "Leda", "Aquarine", "Lapeyre"
    ],
    "cuisine": [
        "Schmidt", "Mobalpa", "IKEA", "Cuisine Plus", "Cuisinella", "Arthur Bonnet", "Snaidero", "Leicht", "Bultaup", "Siemens", "Bosch", "Whirlpool", "Electrolux", "De Dietrich", "Brandt"
    ],
    "luminaire": [
        "Philips", "Osram", "Eglo", "Paulmann", "Lucide", "Artemide", "Faro Barcelona", "Massive", "Slamp", "Flos", "Kartell", "Luceplan", "Vibia", "Trio Lighting", "Mantra"
    ],
    "électricité et domotique": [
        "Legrand", "Schneider Electric", "Somfy", "Netatmo", "Delta Dore", "Bosch Smart Home", "Philips Hue", "Fibaro", "Nodon", "Gira", "Hager", "BTicino", "ABB", "Siemens", "Eaton"
    ],
    "quincaillerie": [
        "Stanley", "Facom", "Bosch", "Makita", "Dexter", "Wolfcraft", "Irwin", "Knipex", "Vachette", "Bricard", "Abus", "Securit", "Tesa", "Laperche", "Thirard"
    ],
    "peinture et droguerie": [
        "Dulux Valentine", "Ripolin", "V33", "Sikkens", "Tollens", "Blancolor", "Guittet", "Levis", "Luxens", "Hammerite", "Julien", "Bondex", "Oxi", "Béton Ciré", "Peintures 1825"
    ],
    "carrelage et parquet": [
        "Porcelanosa", "Marazzi", "Cotto d'Este", "Tarkett", "Gerflor", "Quick-Step", "BerryAlloc", "Pergo", "Lapeyre", "Castorama", "Leroy Merlin", "Saint Maclou", "Alsapan", "Parador", "Wicanders"
    ],
    "matériaux de construction": [
        "Lafarge", "Saint-Gobain", "Knauf", "Isover", "Placo", "Weber", "ParexLanko", "Siniat", "Rockwool", "Siporex", "Point P", "BigMat", "Gedimat", "Bricoman", "Brico Dépôt"
    ]
}
# produit(nom_produit, gamme, type_usine, [(composant, quantite), ...])
PRODUITS = [
    # Produits de chaine assemblage
    ("Tondeuse électrique", "jardin et piscine", "chaine assemblage", [("Vis inox", 20), ("Boulon acier", 10), ("Câble acier", 2)]),
    ("Tondeuse thermique", "jardin et piscine", "chaine assemblage", [("Vis inox", 25), ("Boulon acier", 15), ("Tube cuivre", 1)]),
    ("Coupe-bordures", "jardin et piscine", "chaine assemblage", [("Vis inox", 15), ("Câble acier", 1)]),
    ("Taille-haie", "jardin et piscine", "chaine assemblage", [("Vis inox", 18), ("Boulon acier", 8)]),
    ("Souffleur", "jardin et piscine", "chaine assemblage", [("Vis inox", 12), ("Tube PER", 1)]),
    ("Scarificateur", "jardin et piscine", "chaine assemblage", [("Vis inox", 30), ("Boulon acier", 20), ("Chaîne acier", 1)]),
    ("Bineuse", "jardin et piscine", "chaine assemblage", [("Vis inox", 16), ("Poignée porte", 2)]),
    ("Pompe piscine", "jardin et piscine", "chaine assemblage", [("Vis inox", 20), ("Boulon acier", 12), ("Tube cuivre", 2), ("Raccord cuivre", 4)]),
    ("Filtre piscine", "jardin et piscine", "chaine assemblage", [("Vis inox", 15), ("Tube PER", 3), ("Vanne d'arrêt", 2)]),
    ("Robot piscine", "jardin et piscine", "chaine assemblage", [("Vis inox", 40), ("Boulon acier", 20), ("Câble acier", 1)]),
    ("Échelle piscine", "jardin et piscine", "chaine assemblage", [("Tube cuivre", 6), ("Boulon acier", 24), ("Vis inox", 30)]),
    ("Bâche piscine", "jardin et piscine", "chaine assemblage", [("Chaîne acier", 4), ("Clou", 50)]),
    ("Alarme piscine", "jardin et piscine", "chaine assemblage", [("Vis inox", 10), ("Boîtier étanche", 1), ("Câble acier", 1)]),
    ("Canapé d'angle", "mobilier intérieur", "chaine assemblage", [("Planche pin", 10), ("Vis inox", 50), ("Boulon acier", 30)]),
    ("Fauteuil relax", "mobilier intérieur", "chaine assemblage", [("Planche chêne", 6), ("Vis inox", 40), ("Boulon acier", 20)]),
    ("Table basse", "mobilier intérieur", "chaine assemblage", [("Planche chêne", 4), ("Vis inox", 30), ("Paumelle", 4)]),
    ("Bibliothèque", "mobilier intérieur", "chaine assemblage", [("Planche pin", 15), ("Vis inox", 60), ("Cheville", 20)]),
    ("Armoire penderie", "mobilier intérieur", "chaine assemblage", [("Planche pin", 20), ("Vis inox", 80), ("Paumelle", 6), ("Poignée porte", 2)]),
    ("Commode", "mobilier intérieur", "chaine assemblage", [("Planche chêne", 12), ("Vis inox", 50), ("Poignée porte", 4)]),
    ("Table à manger", "mobilier intérieur", "chaine assemblage", [("Planche chêne", 8), ("Vis inox", 40), ("Boulon acier", 16)]),
    ("Chaises", "mobilier intérieur", "chaine assemblage", [("Planche pin", 4), ("Vis inox", 20), ("Boulon acier", 8)]),
    ("Lit", "mobilier intérieur", "chaine assemblage", [("Planche chêne", 12), ("Vis inox", 60), ("Boulon acier", 40)]),
    ("Matelas", "mobilier intérieur", "chaine assemblage", []),
    ("Sommier", "mobilier intérieur", "chaine assemblage", [("Planche pin", 10), ("Vis inox", 40), ("Boulon acier", 30)]),
    ("Table de chevet", "mobilier intérieur", "chaine assemblage", [("Planche chêne", 4), ("Vis inox", 20), ("Poignée porte", 1)]),
    ("Bureau", "mobilier intérieur", "chaine assemblage", [("Planche chêne", 8), ("Vis inox", 40), ("Boulon acier", 20), ("Poignée porte", 3)]),
    ("Étagères", "mobilier intérieur", "chaine assemblage", [("Planche pin", 6), ("Vis inox", 30), ("Cheville", 12)]),
    ("Perceuse visseuse", "matériaux de construction", "chaine assemblage", [("Vis inox", 15), ("Boulon acier", 10)]),
    ("Perceuse à percussion", "matériaux de construction", "chaine assemblage", [("Vis inox", 18), ("Boulon acier", 12)]),
    ("Visseuse impact", "matériaux de construction", "chaine assemblage", [("Vis inox", 20), ("Boulon acier", 15)]),
    ("Scie circulaire", "matériaux de construction", "chaine assemblage", [("Vis inox", 25), ("Boulon acier", 18)]),
    ("Scie sauteuse", "matériaux de construction", "chaine assemblage", [("Vis inox", 20), ("Boulon acier", 12)]),
    ("Ponceuse orbitale", "matériaux de construction", "chaine assemblage", [("Vis inox", 15), ("Boulon acier", 10)]),
    ("Ponceuse excentrique", "matériaux de construction", "chaine assemblage", [("Vis inox", 18), ("Boulon acier", 12)]),
    ("Défonceuse", "matériaux de construction", "chaine assemblage", [("Vis inox", 22), ("Boulon acier", 16)]),
    ("Raboteuse", "matériaux de construction", "chaine assemblage", [("Vis inox", 30), ("Boulon acier", 20)]),
    ("Meuleuse", "matériaux de construction", "chaine assemblage", [("Vis inox", 18), ("Boulon acier", 14)]),
    ("Perforateur", "matériaux de construction", "chaine assemblage", [("Vis inox", 25), ("Boulon acier", 18)]),
    ("Marteau piqueur", "matériaux de construction", "chaine assemblage", [("Vis inox", 30), ("Boulon acier", 25)]),
    ("Tableau électrique CA", "électricité et domotique", "chaine assemblage", [("Vis inox", 40), ("Rail DIN", 5), ("Borne connexion", 10)]),
    ("Disjoncteur CA", "électricité et domotique", "chaine assemblage", [("Vis inox", 8), ("Borne connexion", 2)]),
    ("Interrupteur différentiel CA", "électricité et domotique", "chaine assemblage", [("Vis inox", 10), ("Borne connexion", 3)]),
    ("Box domotique", "électricité et domotique", "chaine assemblage", [("Vis inox", 12), ("Boîtier étanche", 1), ("Borne connexion", 8)]),
    ("Prise connectée", "électricité et domotique", "chaine assemblage", [("Vis inox", 4), ("Borne connexion", 2)]),
    ("Interrupteur connecté", "électricité et domotique", "chaine assemblage", [("Vis inox", 4), ("Borne connexion", 2)]),
    ("Détecteur mouvement", "électricité et domotique", "chaine assemblage", [("Vis inox", 6), ("Boîtier étanche", 1)]),
    ("Caméra surveillance", "électricité et domotique", "chaine assemblage", [("Vis inox", 8), ("Boîtier étanche", 1), ("Câble acier", 1)]),
    ("Portier vidéo", "électricité et domotique", "chaine assemblage", [("Vis inox", 10), ("Boîtier étanche", 1), ("Borne connexion", 4)]),

    # Produits de scierie (pas de composants - matières premières)
    ("Planche pin", "jardin et piscine", "scierie", []),
    ("Planche chêne", "jardin et piscine", "scierie", []),
    ("Lame terrasse", "jardin et piscine", "scierie", []),
    ("Poteau bois", "jardin et piscine", "scierie", []),
    ("Panneau bois", "jardin et piscine", "scierie", []),
    ("Bardage bois", "jardin et piscine", "scierie", []),
    ("Cloture bois", "jardin et piscine", "scierie", []),
    ("Pergola bois", "jardin et piscine", "scierie", []),
    ("Abri jardin", "jardin et piscine", "scierie", []),
    ("Jardinière bois", "jardin et piscine", "scierie", []),
    ("Bac à sable", "jardin et piscine", "scierie", []),
    ("Balançoire", "jardin et piscine", "scierie", []),
    ("Plan travail bois", "mobilier intérieur", "scierie", []),
    ("Étagère pin", "mobilier intérieur", "scierie", []),
    ("Étagère chêne", "mobilier intérieur", "scierie", []),
    ("Planche étagère", "mobilier intérieur", "scierie", []),
    ("Tasseau bois", "mobilier intérieur", "scierie", []),
    ("Moulure bois", "mobilier intérieur", "scierie", []),
    ("Corniche bois", "mobilier intérieur", "scierie", []),
    ("Plinthe bois", "mobilier intérieur", "scierie", []),
    ("Parquet massif", "mobilier intérieur", "scierie", []),
    ("Parquet contrecollé", "mobilier intérieur", "scierie", []),
    ("Stratifié", "mobilier intérieur", "scierie", []),
    ("Lambris", "mobilier intérieur", "scierie", []),
    ("Parquet chêne massif", "carrelage et parquet", "scierie", []),
    ("Parquet hêtre", "carrelage et parquet", "scierie", []),
    ("Parquet bambou", "carrelage et parquet", "scierie", []),
    ("Parquet flottant", "carrelage et parquet", "scierie", []),
    ("Lame PVC", "carrelage et parquet", "scierie", []),
    ("Sol vinyle", "carrelage et parquet", "scierie", []),
    ("Sous-couche parquet", "carrelage et parquet", "scierie", []),
    ("Carrelage mural 20x20cm", "carrelage et parquet", "fonderie", []),
    ("Carrelage sol 30x30cm", "carrelage et parquet", "fonderie", []),
    ("Carrelage imitation bois", "carrelage et parquet", "fonderie", []),
    ("Carrelage mosaïque", "carrelage et parquet", "fonderie", []),
    ("Plinthes carrelage", "carrelage et parquet", "fonderie", []),
    ("Joint carrelage blanc 5kg", "carrelage et parquet", "chaine assemblage", []),
    ("Joint carrelage gris 5kg", "carrelage et parquet", "chaine assemblage", []),
    ("Colle carrelage 25kg", "carrelage et parquet", "chaine assemblage", []),
    ("Primaire d'accrochage sol", "carrelage et parquet", "chaine assemblage", []),
    ("Profilé finition alu", "carrelage et parquet", "métallurgie", []),
    ("Baguette angle carrelage", "carrelage et parquet", "métallurgie", []),
    ("Croisillons 2mm x100", "carrelage et parquet", "chaine assemblage", []),
    ("Niveau laser carreleur", "carrelage et parquet", "chaine assemblage", [("Vis inox", 8), ("Boîtier étanche", 1)]),
    ("Coupe-carreaux manuel", "carrelage et parquet", "chaine assemblage", [("Vis inox", 15), ("Boulon acier", 10)]),
    ("Meuleuse carrelage", "carrelage et parquet", "chaine assemblage", [("Vis inox", 20), ("Boulon acier", 12)]),
    ("Disque diamant carrelage", "carrelage et parquet", "métallurgie", []),
    ("Poutre bois", "matériaux de construction", "scierie", []),
    ("Chevron", "matériaux de construction", "scierie", []),
    ("Latte", "matériaux de construction", "scierie", []),
    ("Madrier", "matériaux de construction", "scierie", []),
    ("Planche coffrage", "matériaux de construction", "scierie", []),
    ("OSB", "matériaux de construction", "scierie", []),
    ("Contreplaqué", "matériaux de construction", "scierie", []),
    ("Médium MDF", "matériaux de construction", "scierie", []),
    ("Aggloméré", "matériaux de construction", "scierie", []),
    ("Panneau OSB", "matériaux de construction", "scierie", []),

    # Produits de métallurgie (pas de composants - matières premières)
    ("Vis inox", "quincaillerie", "métallurgie", []),
    ("Boulon acier", "quincaillerie", "métallurgie", []),
    ("Écrou", "quincaillerie", "métallurgie", []),
    ("Rondelle", "quincaillerie", "métallurgie", []),
    ("Clou", "quincaillerie", "métallurgie", []),
    ("Pointe", "quincaillerie", "métallurgie", []),
    ("Cheville", "quincaillerie", "métallurgie", []),
    ("Tire-fond", "quincaillerie", "métallurgie", []),
    ("Tige filetée", "quincaillerie", "métallurgie", []),
    ("Chaîne acier", "quincaillerie", "métallurgie", []),
    ("Câble acier", "quincaillerie", "métallurgie", []),
    ("Serrure", "quincaillerie", "métallurgie", []),
    ("Verrou", "quincaillerie", "métallurgie", []),
    ("Cadenas", "quincaillerie", "métallurgie", []),
    ("Gond", "quincaillerie", "métallurgie", []),
    ("Paumelle", "quincaillerie", "métallurgie", []),
    ("Charnière", "quincaillerie", "métallurgie", []),
    ("Tube cuivre", "plomberie et chauffage", "métallurgie", []),
    ("Raccord cuivre", "plomberie et chauffage", "métallurgie", []),
    ("Tube PER", "plomberie et chauffage", "métallurgie", []),
    ("Raccord PER", "plomberie et chauffage", "métallurgie", []),
    ("Radiateur acier", "plomberie et chauffage", "métallurgie", []),
    ("Radiateur fonte", "plomberie et chauffage", "métallurgie", []),
    ("Collecteur chauffage", "plomberie et chauffage", "métallurgie", []),
    ("Vanne d'arrêt", "plomberie et chauffage", "métallurgie", []),
    ("Clapet anti-retour", "plomberie et chauffage", "métallurgie", []),
    ("Détendeur gaz", "plomberie et chauffage", "métallurgie", []),
    ("Gaine électrique", "électricité et domotique", "métallurgie", []),
    ("Tube IRL", "électricité et domotique", "métallurgie", []),
    ("Chemin câbles", "électricité et domotique", "métallurgie", []),
    ("Goulottes", "électricité et domotique", "métallurgie", []),
    ("Boîtier étanche", "électricité et domotique", "métallurgie", []),
    ("Armoire électrique", "électricité et domotique", "métallurgie", []),
    ("Rail DIN", "électricité et domotique", "métallurgie", []),
    ("Borne connexion", "électricité et domotique", "métallurgie", []),
    ("Clé plate", "matériaux de construction", "métallurgie", []),
    ("Clé à pipe", "matériaux de construction", "métallurgie", []),
    ("Tournevis", "matériaux de construction", "métallurgie", []),
    ("Pince", "matériaux de construction", "métallurgie", []),
    ("Serre-joint", "matériaux de construction", "métallurgie", []),
    ("Étau", "matériaux de construction", "métallurgie", []),
    ("Lime", "matériaux de construction", "métallurgie", []),
    ("Râpe", "matériaux de construction", "métallurgie", []),
    ("Burins", "matériaux de construction", "métallurgie", []),
    ("Pointeau", "matériaux de construction", "métallurgie", []),
    ("Compas", "matériaux de construction", "métallurgie", []),

    # Produits de fonderie
    ("Mitigeur cuisine", "plomberie et chauffage", "fonderie", []),
    ("Mitigeur douche", "plomberie et chauffage", "fonderie", []),
    ("Robinet lavabo", "plomberie et chauffage", "fonderie", []),
    ("Robinet évier", "plomberie et chauffage", "fonderie", []),
    ("Douchette", "plomberie et chauffage", "fonderie", []),
    ("Colonne douche", "plomberie et chauffage", "fonderie", []),
    ("Bonde", "plomberie et chauffage", "fonderie", []),
    ("Siphon", "plomberie et chauffage", "fonderie", []),
    ("Collecteur fonte", "plomberie et chauffage", "fonderie", []),
    ("Regard fonte", "plomberie et chauffage", "fonderie", []),
    ("Bouche égout", "plomberie et chauffage", "fonderie", []),
    ("Robinet baignoire", "salle de bain et WC", "fonderie", []),
    ("Mitigeur thermostatique", "salle de bain et WC", "fonderie", []),
    ("Pomme douche", "salle de bain et WC", "fonderie", []),
    ("Flexible douche", "salle de bain et WC", "fonderie", []),
    ("Barre douche", "salle de bain et WC", "fonderie", []),
    ("Support douchette", "salle de bain et WC", "fonderie", []),
    ("Évacuation douche", "salle de bain et WC", "fonderie", []),
    ("Bonde baignoire", "salle de bain et WC", "fonderie", []),
    ("Trop-plein", "salle de bain et WC", "fonderie", []),
    ("Baignoire acrylique 170cm", "salle de bain et WC", "chaine assemblage", [("Vis inox", 30), ("Boulon acier", 20)]),
    ("Baignoire îlot", "salle de bain et WC", "chaine assemblage", [("Vis inox", 40), ("Boulon acier", 25)]),
    ("Receveur douche 90x90cm", "salle de bain et WC", "fonderie", []),
    ("Receveur extra-plat", "salle de bain et WC", "fonderie", []),
    ("Paroi douche verre", "salle de bain et WC", "chaine assemblage", [("Vis inox", 20), ("Rail DIN", 4)]),
    ("Cabine douche complète", "salle de bain et WC", "chaine assemblage", [("Vis inox", 50), ("Boulon acier", 30), ("Tube cuivre", 2)]),
    ("Meuble vasque 80cm", "salle de bain et WC", "chaine assemblage", [("Planche pin", 8), ("Vis inox", 40), ("Poignée porte", 2)]),
    ("Vasque à poser", "salle de bain et WC", "fonderie", []),
    ("Vasque encastrable", "salle de bain et WC", "fonderie", []),
    ("WC suspendu", "salle de bain et WC", "fonderie", []),
    ("WC au sol", "salle de bain et WC", "fonderie", []),
    ("Abattant WC", "salle de bain et WC", "chaine assemblage", [("Vis inox", 4)]),
    ("Meuble colonne SDB", "salle de bain et WC", "chaine assemblage", [("Planche pin", 10), ("Vis inox", 50), ("Paumelle", 2)]),
    ("Miroir lumineux LED", "salle de bain et WC", "chaine assemblage", [("Vis inox", 10), ("Borne connexion", 4)]),
    ("Sèche-serviette électrique", "salle de bain et WC", "chaine assemblage", [("Vis inox", 15), ("Borne connexion", 6)]),
    ("Applique murale", "luminaire", "fonderie", []),
    ("Suspension", "luminaire", "fonderie", []),
    ("Lustre", "luminaire", "fonderie", []),
    ("Spot encastrable", "luminaire", "fonderie", []),
    ("Réglette LED", "luminaire", "fonderie", []),
    ("Plafonnier", "luminaire", "fonderie", []),
    ("Lampadaire", "luminaire", "fonderie", []),
    ("Lampe bureau", "luminaire", "fonderie", []),
    ("Projecteur LED", "luminaire", "fonderie", []),
    ("Borne éclairage", "luminaire", "fonderie", []),
    ("Balise LED", "luminaire", "fonderie", []),
    ("Ruban LED 5m", "luminaire", "chaine assemblage", [("Borne connexion", 2)]),
    ("Transformateur LED", "luminaire", "chaine assemblage", [("Vis inox", 4), ("Borne connexion", 3)]),
    ("Variateur lumière", "luminaire", "chaine assemblage", [("Vis inox", 2), ("Borne connexion", 2)]),
    ("Ampoule LED E27", "luminaire", "chaine assemblage", []),
    ("Ampoule LED E14", "luminaire", "chaine assemblage", []),
    ("Tube LED T8", "luminaire", "chaine assemblage", []),
    ("Guirlande lumineuse", "luminaire", "chaine assemblage", []),
    ("Lampe chevet tactile", "luminaire", "chaine assemblage", [("Vis inox", 6), ("Borne connexion", 2)]),
    ("Lampe architecte", "luminaire", "chaine assemblage", [("Vis inox", 10), ("Boulon acier", 6)]),
    ("Hublot extérieur", "luminaire", "fonderie", []),
    ("Détecteur crépusculaire", "luminaire", "chaine assemblage", [("Vis inox", 4), ("Boîtier étanche", 1)]),
    ("Minuterie éclairage", "luminaire", "chaine assemblage", [("Vis inox", 4), ("Borne connexion", 3)]),
    ("Rail spots LED", "luminaire", "métallurgie", []),
    ("Tableau électrique FO", "électricité et domotique", "fonderie", []),
    ("Disjoncteur FO", "électricité et domotique", "fonderie", []),
    ("Interrupteur différentiel FO", "électricité et domotique", "fonderie", []),
    ("Box domotique FO", "électricité et domotique", "fonderie", []),
    ("Prise connectée FO", "électricité et domotique", "fonderie", []),
    ("Interrupteur connecté FO", "électricité et domotique", "fonderie", []),
    ("Détecteur mouvement FO", "électricité et domotique", "fonderie", []),
    ("Caméra surveillance FO", "électricité et domotique", "fonderie", []),
    ("Portier vidéo FO", "électricité et domotique", "fonderie", []),
    ("Poignée porte", "quincaillerie", "fonderie", []),
    ("Béquille", "quincaillerie", "fonderie", []),
    ("Crémone", "quincaillerie", "fonderie", []),
    ("Espagnolette", "quincaillerie", "fonderie", []),
    ("Ferme-porte", "quincaillerie", "fonderie", []),
    ("Butée porte", "quincaillerie", "fonderie", []),
    ("Heurtoir", "quincaillerie", "fonderie", []),
    ("Boîte aux lettres", "quincaillerie", "fonderie", []),

    # Produits pour la gamme "cuisine"
    ("Meuble bas cuisine 60cm", "cuisine", "chaine assemblage", [("Planche pin", 8), ("Vis inox", 40), ("Paumelle", 2), ("Poignée porte", 1)]),
    ("Meuble haut cuisine 80cm", "cuisine", "chaine assemblage", [("Planche pin", 6), ("Vis inox", 30), ("Paumelle", 2), ("Poignée porte", 1)]),
    ("Meuble évier 120cm", "cuisine", "chaine assemblage", [("Planche pin", 10), ("Vis inox", 50), ("Paumelle", 2)]),
    ("Meuble colonne four", "cuisine", "chaine assemblage", [("Planche pin", 12), ("Vis inox", 60), ("Paumelle", 4), ("Poignée porte", 2)]),
    ("Plan travail stratifié 240cm", "cuisine", "scierie", []),
    ("Plan travail bois massif", "cuisine", "scierie", []),
    ("Crédence carrelage", "cuisine", "chaine assemblage", []),
    ("Hotte aspirante murale", "cuisine", "chaine assemblage", [("Vis inox", 20), ("Boulon acier", 10), ("Tube cuivre", 1)]),
    ("Hotte îlot", "cuisine", "chaine assemblage", [("Vis inox", 25), ("Boulon acier", 12), ("Chaîne acier", 2)]),
    ("Évier inox 1 bac", "cuisine", "métallurgie", []),
    ("Évier inox 2 bacs", "cuisine", "métallurgie", []),
    ("Évier céramique", "cuisine", "fonderie", []),
    ("Mitigeur évier design", "cuisine", "fonderie", []),
    ("Robinet douchette", "cuisine", "fonderie", []),
    ("Tiroir coulissant", "cuisine", "chaine assemblage", [("Vis inox", 15), ("Rail DIN", 2)]),
    ("Plateau tournant angle", "cuisine", "chaine assemblage", [("Vis inox", 10), ("Rondelle", 8)]),
    ("Poubelle encastrable", "cuisine", "chaine assemblage", [("Vis inox", 8)]),
    ("Range-épices", "cuisine", "chaine assemblage", [("Vis inox", 6)]),
    ("Étagère murale inox", "cuisine", "métallurgie", []),
    ("Barre crédence", "cuisine", "métallurgie", []),
    ("Poignée meuble inox", "cuisine", "métallurgie", []),
    ("Charnière invisible", "cuisine", "métallurgie", []),
    ("Rail tiroir", "cuisine", "métallurgie", []),
    ("Plinthe cuisine", "cuisine", "scierie", []),
    ("Corniche finition", "cuisine", "scierie", []),

    # Produits pour la gamme "peinture et droguerie"
    ("Peinture acrylique intérieure 2.5L", "peinture et droguerie", "chaine assemblage", []),
    ("Peinture glycéro 2.5L", "peinture et droguerie", "chaine assemblage", []),
    ("Sous-couche universelle 5L", "peinture et droguerie", "chaine assemblage", []),
    ("Enduit de rebouchage 1kg", "peinture et droguerie", "chaine assemblage", []),
    ("Enduit de lissage 5kg", "peinture et droguerie", "chaine assemblage", []),
    ("Ponçeuse multi-usages", "peinture et droguerie", "chaine assemblage", [("Vis inox", 5)]),
    ("Brosse à peinture 50mm", "peinture et droguerie", "chaine assemblage", []),
    ("Rouleau 18cm", "peinture et droguerie", "chaine assemblage", []),
    ("Bâche protection 4x5m", "peinture et droguerie", "chaine assemblage", []),
    ("Ruban de masquage 50mm", "peinture et droguerie", "chaine assemblage", []),
    ("Décapant peinture 1L", "peinture et droguerie", "chaine assemblage", []),
    ("Diluant / White spirit 5L", "peinture et droguerie", "chaine assemblage", []),
    ("Vernis bois 1L", "peinture et droguerie", "chaine assemblage", []),
    ("Lasur bois 2.5L", "peinture et droguerie", "chaine assemblage", []),
    ("Nettoyant mur 1L", "peinture et droguerie", "chaine assemblage", []),
    ("Peinture extérieure 10L", "peinture et droguerie", "chaine assemblage", []),
    ("Primaire accrochage", "peinture et droguerie", "chaine assemblage", []),
    ("Laque brillante", "peinture et droguerie", "chaine assemblage", []),
    ("Peinture tableau noir", "peinture et droguerie", "chaine assemblage", []),
    ("Anti-rouille", "peinture et droguerie", "chaine assemblage", []),
]