TYPEU = ["chaine assemblage", "scierie", "métallurgie", "fonderie"]

GAMMES = [
    "jardin et piscine", "mobilier intérieur", "plomberie et chauffage", "salle de bain et WC",
    "luminaire", "électricité et domotique", "quincaillerie", "cuisine",
    "peinture et droguerie", "carrelage et parquet", "matériaux de construction"
]

DEPTS = ["fabrication", "assemblage", "RH", "expédition", "logistique", "direction", "finance"]

PV_TYPES = ["GSB", "Brico-Express"]

PV_NAMES = {
    "GSB": [
        "Brico Dépôt", "Leroy Merlin", "Castorama", "Weldom", "Bricomarché",
        "Point P", "Gedimat", "BigMat", "Brico Pro", "Mr.Bricolage",
        "Bricoman", "Brico Cash", "La Plateforme du Bâtiment", "Brico Leclerc",
        "Brico Centre", "Entrepôt du Bricolage", "Brico Arche", "King Jouet Bricolage"
    ],
    "Brico-Express": [
        "Brico Minute", "Brico Shop", "Brico Corner", "Express Bricolage",
        "Brico Plus", "Quick Brico", "Brico Service", "Brico Direct",
        "Brico Rapide", "Brico Point", "Allo Brico", "Brico Store",
        "Brico Facile", "Flash Brico", "Brico Express +", "Top Brico"
    ]
}


NOMS = [
    *( [
        "Martin", "Bernard", "Thomas", "Petit", "Robert", "Richard", "Durand", "Dubois",
        "Moreau", "Laurent", "Simon", "Michel", "Lefebvre", "Leroy", "Roux", "David", "Foxy"
    ] * 5 ),
]

PRENOMS = [
    *( [
        "Lucas", "Louis", "Hugo", "Arthur", "Jules", "Adam", "Léo", "Noah",
        "Emma", "Louise", "Chloé", "Lina", "Mia", "Anna", "Zoé", "Léa"
    ] * 5 ),
]

# Bases
QUALIFICATIONS_PROBABILITIES = {
    3: 0.20,  # CAP, BEP
    4: 0.30,  # Bac Pro, BP, Bac
    5: 0.20,  # BTS, DUT
    6: 0.15,  # Licence Pro, BUT, Licence
    7: 0.10,   # Master
    8: 0.05,   # Doctorat
}

QUALIFICATIONS = {
    # Niveau: [(diplome_complet, salaire_min, salaire_max, base_diplome)]
    3: [
        # Bases
        ("CAP", 11.0, 15.0),
        ("BEP", 11.5, 15.0),
        # Spécialisations
        ("CAP Électricien", 11.5, 16.0, "CAP"),
        ("BEP Chaîne Assemblage", 11.5, 15.0, "BEP"),
        ("BEP Scierie", 11.5, 15.0, "BEP"),
        ("BEP Métallurgie", 11.5, 15.0, "BEP"),
        ("BEP Fonderie", 11.5, 15.0, "BEP"),
        ("BEP Fabrication", 11.5, 15.0, "BEP"),
        ("BEP Assemblage", 11.5, 15.0, "BEP"),
        ("BEP RH", 11.5, 15.0, "BEP"),
        ("BEP Expédition", 11.5, 15.0, "BEP"),
        ("BEP Logistique", 11.5, 15.0, "BEP"),
        ("BEP Direction", 11.5, 15.0, "BEP"),
        ("BEP Finance", 11.5, 15.0, "BEP"),
        ("CAP Chaîne Assemblage", 11.0, 15.0, "CAP"),
        ("CAP Scierie", 11.0, 15.0, "CAP"),
        ("CAP Métallurgie", 11.0, 15.0, "CAP"),
        ("CAP Fonderie", 11.0, 15.0, "CAP"),
        ("CAP Fabrication", 11.0, 15.0, "CAP"),
        ("CAP Assemblage", 11.0, 15.0, "CAP"),
        ("CAP RH", 11.0, 15.0, "CAP"),
        ("CAP Expédition", 11.0, 15.0, "CAP"),
        ("CAP Logistique", 11.0, 15.0, "CAP"),
        ("CAP Direction", 11.0, 15.0, "CAP"),
        ("CAP Finance", 11.0, 15.0, "CAP"),
    ],
    4: [
        # Bases
        ("Bac Pro", 13.0, 17.0),
        ("BP", 14.0, 18.0),
        ("Bac", 13.0, 16.5),
        # Spécialisations BP
        ("BP Chaîne Assemblage", 14.0, 18.0, "BP"),
        ("BP Scierie", 14.0, 18.0, "BP"),
        ("BP Métallurgie", 14.0, 18.0, "BP"),
        ("BP Fonderie", 14.0, 18.0, "BP"),
        ("BP Fabrication", 14.0, 18.0, "BP"),
        ("BP Assemblage", 14.0, 18.0, "BP"),
        ("BP RH", 14.0, 18.0, "BP"),
        ("BP Expédition", 14.0, 18.0, "BP"),
        ("BP Logistique", 14.0, 18.0, "BP"),
        ("BP Direction", 14.0, 18.0, "BP"),
        ("BP Finance", 14.0, 18.0, "BP"),
        # Spécialisations Bac Pro
        ("Bac Pro Électrotechnique", 13.5, 18.0, "Bac Pro"),
        ("Bac Pro Chaîne Assemblage", 13.0, 17.0, "Bac Pro"),
        ("Bac Pro Scierie", 13.0, 17.0, "Bac Pro"),
        ("Bac Pro Métallurgie", 13.0, 17.0, "Bac Pro"),
        ("Bac Pro Fonderie", 13.0, 17.0, "Bac Pro"),
        ("Bac Pro Fabrication", 13.0, 17.0, "Bac Pro"),
        ("Bac Pro Assemblage", 13.0, 17.0, "Bac Pro"),
        ("Bac Pro RH", 13.0, 17.0, "Bac Pro"),
        ("Bac Pro Expédition", 13.0, 17.0, "Bac Pro"),
        ("Bac Pro Logistique", 13.0, 17.0, "Bac Pro"),
        ("Bac Pro Direction", 13.0, 17.0, "Bac Pro"),
        ("Bac Pro Finance", 13.0, 17.0, "Bac Pro"),
    ],
    5: [
        # Bases
        ("BTS", 15.0, 22.0),
        ("DUT", 15.5, 22.0),
        # Spécialisations
        ("DUT Chaîne Assemblage", 15.5, 22.0, "DUT"),
        ("DUT Scierie", 15.5, 22.0, "DUT"),
        ("DUT Métallurgie", 15.5, 22.0, "DUT"),
        ("DUT Fonderie", 15.5, 22.0, "DUT"),
        ("DUT Fabrication", 15.5, 22.0, "DUT"),
        ("DUT Assemblage", 15.5, 22.0, "DUT"),
        ("DUT RH", 15.5, 22.0, "DUT"),
        ("DUT Expédition", 15.5, 22.0, "DUT"),
        ("DUT Logistique", 15.5, 22.0, "DUT"),
        ("DUT Direction", 15.5, 22.0, "DUT"),
        ("DUT Finance", 15.5, 22.0, "DUT"),
        ("BTS Électrotechnique", 15.5, 23.0, "BTS"),
        ("BTS Chaîne Assemblage", 15.0, 22.0, "BTS"),
        ("BTS Scierie", 15.0, 22.0, "BTS"),
        ("BTS Métallurgie", 15.0, 22.0, "BTS"),
        ("BTS Fonderie", 15.0, 22.0, "BTS"),
        ("BTS Fabrication", 15.0, 22.0, "BTS"),
        ("BTS Assemblage", 15.0, 22.0, "BTS"),
        ("BTS RH", 15.0, 22.0, "BTS"),
        ("BTS Expédition", 15.0, 22.0, "BTS"),
        ("BTS Logistique", 15.0, 22.0, "BTS"),
        ("BTS Direction", 15.0, 22.0, "BTS"),
        ("BTS Finance", 15.0, 22.0, "BTS"),
    ],
    6: [
        # Bases
        ("Licence Pro", 18.0, 24.0),
        ("BUT", 18.5, 25.0),
        ("Licence", 18.0, 23.5),
        # Spécialisations Licence Pro
        ("Licence Pro Chaîne Assemblage", 18.0, 24.0, "Licence Pro"),
        ("Licence Pro Scierie", 18.0, 24.0, "Licence Pro"),
        ("Licence Pro Métallurgie", 18.0, 24.0, "Licence Pro"),
        ("Licence Pro Fonderie", 18.0, 24.0, "Licence Pro"),
        ("Licence Pro Fabrication", 18.0, 24.0, "Licence Pro"),
        ("Licence Pro Assemblage", 18.0, 24.0, "Licence Pro"),
        ("Licence Pro RH", 18.0, 24.0, "Licence Pro"),
        ("Licence Pro Expédition", 18.0, 24.0, "Licence Pro"),
        ("Licence Pro Logistique", 18.0, 24.0, "Licence Pro"),
        ("Licence Pro Direction", 18.0, 24.0, "Licence Pro"),
        ("Licence Pro Finance", 18.0, 24.0, "Licence Pro"),
        # Spécialisations BUT
        ("BUT Chaîne Assemblage", 18.5, 25.0, "BUT"),
        ("BUT Scierie", 18.5, 25.0, "BUT"),
        ("BUT Métallurgie", 18.5, 25.0, "BUT"),
        ("BUT Fonderie", 18.5, 25.0, "BUT"),
        ("BUT Fabrication", 18.5, 25.0, "BUT"),
        ("BUT Assemblage", 18.5, 25.0, "BUT"),
        ("BUT RH", 18.5, 25.0, "BUT"),
        ("BUT Expédition", 18.5, 25.0, "BUT"),
        ("BUT Logistique", 18.5, 25.0, "BUT"),
        ("BUT Direction", 18.5, 25.0, "BUT"),
        ("BUT Finance", 18.5, 25.0, "BUT"),
        # Spécialisations Licence
        ("Licence Pro Métiers de l'Électricité", 18.5, 25.0, "Licence"),
        ("Licence Chaîne Assemblage", 18.0, 23.5, "Licence"),
        ("Licence Scierie", 18.0, 23.5, "Licence"),
        ("Licence Métallurgie", 18.0, 23.5, "Licence"),
        ("Licence Fonderie", 18.0, 23.5, "Licence"),
        ("Licence Fabrication", 18.0, 23.5, "Licence"),
        ("Licence Assemblage", 18.0, 23.5, "Licence"),
        ("Licence RH", 18.0, 23.5, "Licence"),
        ("Licence Expédition", 18.0, 23.5, "Licence"),
        ("Licence Logistique", 18.0, 23.5, "Licence"),
        ("Licence Direction", 18.0, 23.5, "Licence"),
        ("Licence Finance", 18.0, 23.5, "Licence"),
    ],
    7: [
        # Bases
        ("Master", 22.0, 30.0),
        ("Ingénieur", 24.0, 35.0),
        # Spécialisations
        ("Ingénieur Chaîne Assemblage", 24.0, 35.0, "Ingénieur"),
        ("Ingénieur Scierie", 24.0, 35.0, "Ingénieur"),
        ("Ingénieur Métallurgie", 24.0, 35.0, "Ingénieur"),
        ("Ingénieur Fonderie", 24.0, 35.0, "Ingénieur"),
        ("Ingénieur Fabrication", 24.0, 35.0, "Ingénieur"),
        ("Ingénieur Assemblage", 24.0, 35.0, "Ingénieur"),
        ("Ingénieur RH", 24.0, 35.0, "Ingénieur"),
        ("Ingénieur Expédition", 24.0, 35.0, "Ingénieur"),
        ("Ingénieur Logistique", 24.0, 35.0, "Ingénieur"),
        ("Ingénieur Direction", 24.0, 35.0, "Ingénieur"),
        ("Ingénieur Finance", 24.0, 35.0, "Ingénieur"),
        ("Master Énergétique et Électrique", 23.0, 32.0, "Master"),
        ("Master Chaîne Assemblage", 22.0, 30.0, "Master"),
        ("Master Scierie", 22.0, 30.0, "Master"),
        ("Master Métallurgie", 22.0, 30.0, "Master"),
        ("Master Fonderie", 22.0, 30.0, "Master"),
        ("Master Fabrication", 22.0, 30.0, "Master"),
        ("Master Assemblage", 22.0, 30.0, "Master"),
        ("Master RH", 22.0, 30.0, "Master"),
        ("Master Expédition", 22.0, 30.0, "Master"),
        ("Master Logistique", 22.0, 30.0, "Master"),
        ("Master Direction", 22.0, 30.0, "Master"),
        ("Master Finance", 22.0, 30.0, "Master"),
    ],
    8: [
        # Bases
        ("Doctorat", 28.0, 40.0),
        # Spécialisations Doctorat
        ("Doctorat en Génie Électrique", 29.0, 42.0, "Doctorat"),
        ("Doctorat Chaîne Assemblage", 28.0, 40.0, "Doctorat"),
        ("Doctorat Scierie", 28.0, 40.0, "Doctorat"),
        ("Doctorat Métallurgie", 28.0, 40.0, "Doctorat"),
        ("Doctorat Fonderie", 28.0, 40.0, "Doctorat"),
        ("Doctorat Fabrication", 28.0, 40.0, "Doctorat"),
        ("Doctorat Assemblage", 28.0, 40.0, "Doctorat"),
        ("Doctorat RH", 28.0, 40.0, "Doctorat"),
        ("Doctorat Expédition", 28.0, 40.0, "Doctorat"),
        ("Doctorat Logistique", 28.0, 40.0, "Doctorat"),
        ("Doctorat Direction", 28.0, 40.0, "Doctorat"),
        ("Doctorat Finance", 28.0, 40.0, "Doctorat"),
    ],
}


# -----------------------
# RECETTES DE PRODUITS
# Format: (nom_produit, gamme, type_usine)
# -----------------------
# create object product
class Product:
    def __init__(self, name, gamme, type_usine):
        self.name = name
        self.gamme = gamme
        self.type_usine = type_usine
        self.recettes = []


RECETTES_PRODUITS = [
    # Produits de chaine assemblage
    ("Tondeuse électrique", "jardin et piscine", "chaine assemblage"),
    ("Tondeuse thermique", "jardin et piscine", "chaine assemblage"),
    ("Coupe-bordures", "jardin et piscine", "chaine assemblage"),
    ("Taille-haie", "jardin et piscine", "chaine assemblage"),
    ("Souffleur", "jardin et piscine", "chaine assemblage"),
    ("Scarificateur", "jardin et piscine", "chaine assemblage"),
    ("Bineuse", "jardin et piscine", "chaine assemblage"),
    ("Pompe piscine", "jardin et piscine", "chaine assemblage"),
    ("Filtre piscine", "jardin et piscine", "chaine assemblage"),
    ("Robot piscine", "jardin et piscine", "chaine assemblage"),
    ("Échelle piscine", "jardin et piscine", "chaine assemblage"),
    ("Bâche piscine", "jardin et piscine", "chaine assemblage"),
    ("Alarme piscine", "jardin et piscine", "chaine assemblage"),
    ("Canapé d'angle", "mobilier intérieur", "chaine assemblage"),
    ("Fauteuil relax", "mobilier intérieur", "chaine assemblage"),
    ("Table basse", "mobilier intérieur", "chaine assemblage"),
    ("Bibliothèque", "mobilier intérieur", "chaine assemblage"),
    ("Armoire penderie", "mobilier intérieur", "chaine assemblage"),
    ("Commode", "mobilier intérieur", "chaine assemblage"),
    ("Table à manger", "mobilier intérieur", "chaine assemblage"),
    ("Chaises", "mobilier intérieur", "chaine assemblage"),
    ("Lit", "mobilier intérieur", "chaine assemblage"),
    ("Matelas", "mobilier intérieur", "chaine assemblage"),
    ("Sommier", "mobilier intérieur", "chaine assemblage"),
    ("Table de chevet", "mobilier intérieur", "chaine assemblage"),
    ("Bureau", "mobilier intérieur", "chaine assemblage"),
    ("Étagères", "mobilier intérieur", "chaine assemblage"),
    ("Perceuse visseuse", "matériaux de construction", "chaine assemblage"),
    ("Perceuse à percussion", "matériaux de construction", "chaine assemblage"),
    ("Visseuse impact", "matériaux de construction", "chaine assemblage"),
    ("Scie circulaire", "matériaux de construction", "chaine assemblage"),
    ("Scie sauteuse", "matériaux de construction", "chaine assemblage"),
    ("Ponceuse orbitale", "matériaux de construction", "chaine assemblage"),
    ("Ponceuse excentrique", "matériaux de construction", "chaine assemblage"),
    ("Défonceuse", "matériaux de construction", "chaine assemblage"),
    ("Raboteuse", "matériaux de construction", "chaine assemblage"),
    ("Meuleuse", "matériaux de construction", "chaine assemblage"),
    ("Perforateur", "matériaux de construction", "chaine assemblage"),
    ("Marteau piqueur", "matériaux de construction", "chaine assemblage"),
    ("Tableau électrique CA", "électricité et domotique", "chaine assemblage"),
    ("Disjoncteur CA", "électricité et domotique", "chaine assemblage"),
    ("Interrupteur différentiel CA", "électricité et domotique", "chaine assemblage"),
    ("Box domotique", "électricité et domotique", "chaine assemblage"),
    ("Prise connectée", "électricité et domotique", "chaine assemblage"),
    ("Interrupteur connecté", "électricité et domotique", "chaine assemblage"),
    ("Détecteur mouvement", "électricité et domotique", "chaine assemblage"),
    ("Caméra surveillance", "électricité et domotique", "chaine assemblage"),
    ("Portier vidéo", "électricité et domotique", "chaine assemblage"),

    # Produits de scierie
    ("Planche pin", "jardin et piscine", "scierie"),
    ("Planche chêne", "jardin et piscine", "scierie"),
    ("Lame terrasse", "jardin et piscine", "scierie"),
    ("Poteau bois", "jardin et piscine", "scierie"),
    ("Panneau bois", "jardin et piscine", "scierie"),
    ("Bardage bois", "jardin et piscine", "scierie"),
    ("Cloture bois", "jardin et piscine", "scierie"),
    ("Pergola bois", "jardin et piscine", "scierie"),
    ("Abri jardin", "jardin et piscine", "scierie"),
    ("Jardinière bois", "jardin et piscine", "scierie"),
    ("Bac à sable", "jardin et piscine", "scierie"),
    ("Balançoire", "jardin et piscine", "scierie"),
    ("Plan travail bois", "mobilier intérieur", "scierie"),
    ("Étagère pin", "mobilier intérieur", "scierie"),
    ("Étagère chêne", "mobilier intérieur", "scierie"),
    ("Planche étagère", "mobilier intérieur", "scierie"),
    ("Tasseau bois", "mobilier intérieur", "scierie"),
    ("Moulure bois", "mobilier intérieur", "scierie"),
    ("Corniche bois", "mobilier intérieur", "scierie"),
    ("Plinthe bois", "mobilier intérieur", "scierie"),
    ("Parquet massif", "mobilier intérieur", "scierie"),
    ("Parquet contrecollé", "mobilier intérieur", "scierie"),
    ("Stratifié", "mobilier intérieur", "scierie"),
    ("Lambris", "mobilier intérieur", "scierie"),
    ("Parquet chêne massif", "carrelage et parquet", "scierie"),
    ("Parquet hêtre", "carrelage et parquet", "scierie"),
    ("Parquet bambou", "carrelage et parquet", "scierie"),
    ("Parquet flottant", "carrelage et parquet", "scierie"),
    ("Lame PVC", "carrelage et parquet", "scierie"),
    ("Sol vinyle", "carrelage et parquet", "scierie"),
    ("Sous-couche parquet", "carrelage et parquet", "scierie"),
    ("Poutre bois", "matériaux de construction", "scierie"),
    ("Chevron", "matériaux de construction", "scierie"),
    ("Latte", "matériaux de construction", "scierie"),
    ("Madrier", "matériaux de construction", "scierie"),
    ("Planche coffrage", "matériaux de construction", "scierie"),
    ("OSB", "matériaux de construction", "scierie"),
    ("Contreplaqué", "matériaux de construction", "scierie"),
    ("Médium MDF", "matériaux de construction", "scierie"),
    ("Aggloméré", "matériaux de construction", "scierie"),
    ("Panneau OSB", "matériaux de construction", "scierie"),

    # Produits de métallurgie
    ("Vis inox", "quincaillerie", "métallurgie"),
    ("Boulon acier", "quincaillerie", "métallurgie"),
    ("Écrou", "quincaillerie", "métallurgie"),
    ("Rondelle", "quincaillerie", "métallurgie"),
    ("Clou", "quincaillerie", "métallurgie"),
    ("Pointe", "quincaillerie", "métallurgie"),
    ("Cheville", "quincaillerie", "métallurgie"),
    ("Tire-fond", "quincaillerie", "métallurgie"),
    ("Tige filetée", "quincaillerie", "métallurgie"),
    ("Chaîne acier", "quincaillerie", "métallurgie"),
    ("Câble acier", "quincaillerie", "métallurgie"),
    ("Serrure", "quincaillerie", "métallurgie"),
    ("Verrou", "quincaillerie", "métallurgie"),
    ("Cadenas", "quincaillerie", "métallurgie"),
    ("Gond", "quincaillerie", "métallurgie"),
    ("Paumelle", "quincaillerie", "métallurgie"),
    ("Charnière", "quincaillerie", "métallurgie"),
    ("Tube cuivre", "plomberie et chauffage", "métallurgie"),
    ("Raccord cuivre", "plomberie et chauffage", "métallurgie"),
    ("Tube PER", "plomberie et chauffage", "métallurgie"),
    ("Raccord PER", "plomberie et chauffage", "métallurgie"),
    ("Radiateur acier", "plomberie et chauffage", "métallurgie"),
    ("Radiateur fonte", "plomberie et chauffage", "métallurgie"),
    ("Collecteur chauffage", "plomberie et chauffage", "métallurgie"),
    ("Vanne d'arrêt", "plomberie et chauffage", "métallurgie"),
    ("Clapet anti-retour", "plomberie et chauffage", "métallurgie"),
    ("Détendeur gaz", "plomberie et chauffage", "métallurgie"),
    ("Gaine électrique", "électricité et domotique", "métallurgie"),
    ("Tube IRL", "électricité et domotique", "métallurgie"),
    ("Chemin câbles", "électricité et domotique", "métallurgie"),
    ("Goulottes", "électricité et domotique", "métallurgie"),
    ("Boîtier étanche", "électricité et domotique", "métallurgie"),
    ("Armoire électrique", "électricité et domotique", "métallurgie"),
    ("Rail DIN", "électricité et domotique", "métallurgie"),
    ("Borne connexion", "électricité et domotique", "métallurgie"),
    ("Clé plate", "matériaux de construction", "métallurgie"),
    ("Clé à pipe", "matériaux de construction", "métallurgie"),
    ("Tournevis", "matériaux de construction", "métallurgie"),
    ("Pince", "matériaux de construction", "métallurgie"),
    ("Serre-joint", "matériaux de construction", "métallurgie"),
    ("Étau", "matériaux de construction", "métallurgie"),
    ("Lime", "matériaux de construction", "métallurgie"),
    ("Râpe", "matériaux de construction", "métallurgie"),
    ("Burins", "matériaux de construction", "métallurgie"),
    ("Pointeau", "matériaux de construction", "métallurgie"),
    ("Compas", "matériaux de construction", "métallurgie"),

    # Produits de fonderie
    ("Mitigeur cuisine", "plomberie et chauffage", "fonderie"),
    ("Mitigeur douche", "plomberie et chauffage", "fonderie"),
    ("Robinet lavabo", "plomberie et chauffage", "fonderie"),
    ("Robinet évier", "plomberie et chauffage", "fonderie"),
    ("Douchette", "plomberie et chauffage", "fonderie"),
    ("Colonne douche", "plomberie et chauffage", "fonderie"),
    ("Bonde", "plomberie et chauffage", "fonderie"),
    ("Siphon", "plomberie et chauffage", "fonderie"),
    ("Collecteur fonte", "plomberie et chauffage", "fonderie"),
    ("Regard fonte", "plomberie et chauffage", "fonderie"),
    ("Bouche égout", "plomberie et chauffage", "fonderie"),
    ("Robinet baignoire", "salle de bain et WC", "fonderie"),
    ("Mitigeur thermostatique", "salle de bain et WC", "fonderie"),
    ("Pomme douche", "salle de bain et WC", "fonderie"),
    ("Flexible douche", "salle de bain et WC", "fonderie"),
    ("Barre douche", "salle de bain et WC", "fonderie"),
    ("Support douchette", "salle de bain et WC", "fonderie"),
    ("Évacuation douche", "salle de bain et WC", "fonderie"),
    ("Bonde baignoire", "salle de bain et WC", "fonderie"),
    ("Trop-plein", "salle de bain et WC", "fonderie"),
    ("Applique murale", "luminaire", "fonderie"),
    ("Suspension", "luminaire", "fonderie"),
    ("Lustre", "luminaire", "fonderie"),
    ("Spot encastrable", "luminaire", "fonderie"),
    ("Réglette LED", "luminaire", "fonderie"),
    ("Plafonnier", "luminaire", "fonderie"),
    ("Lampadaire", "luminaire", "fonderie"),
    ("Lampe bureau", "luminaire", "fonderie"),
    ("Projecteur LED", "luminaire", "fonderie"),
    ("Borne éclairage", "luminaire", "fonderie"),
    ("Balise LED", "luminaire", "fonderie"),
    ("Tableau électrique FO", "électricité et domotique", "fonderie"),
    ("Disjoncteur FO", "électricité et domotique", "fonderie"),
    ("Interrupteur différentiel FO", "électricité et domotique", "fonderie"),
    ("Box domotique FO", "électricité et domotique", "fonderie"),
    ("Prise connectée FO", "électricité et domotique", "fonderie"),
    ("Interrupteur connecté FO", "électricité et domotique", "fonderie"),
    ("Détecteur mouvement FO", "électricité et domotique", "fonderie"),
    ("Caméra surveillance FO", "électricité et domotique", "fonderie"),
    ("Portier vidéo FO", "électricité et domotique", "fonderie"),
    ("Poignée porte", "quincaillerie", "fonderie"),
    ("Béquille", "quincaillerie", "fonderie"),
    ("Crémone", "quincaillerie", "fonderie"),
    ("Espagnolette", "quincaillerie", "fonderie"),
    ("Ferme-porte", "quincaillerie", "fonderie"),
    ("Butée porte", "quincaillerie", "fonderie"),
    ("Heurtoir", "quincaillerie", "fonderie"),
    ("Boîte aux lettres", "quincaillerie", "fonderie"),
]